# Generated by Django 3.1.4 on 2021-09-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('last_modified', 'name')},
        ),
    ]
