# Generated by Django 3.1.4 on 2021-10-14 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('other_numbers', models.TextField(blank=True, help_text='Enter phone numbers seperated by commas (,)')),
                ('is_draft', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('recipients', models.ManyToManyField(blank=True, related_name='received_sms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_modified',),
            },
        ),
    ]
