# Generated by Django 3.1.4 on 2021-10-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20211018_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='message',
            field=models.TextField(),
        ),
    ]
