# Generated by Django 3.1.4 on 2021-09-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_payment_paystack_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paystack_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
