# Generated by Django 3.1.4 on 2021-08-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210820_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='single_item_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
