# Generated by Django 3.1.4 on 2021-08-24 17:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 24, 17, 33, 30, 795107, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
