# Generated by Django 3.1.4 on 2021-09-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='ref_number',
            new_name='ref_code',
        ),
    ]
