# Generated by Django 3.1.4 on 2021-10-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20211018_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
